# docs: https://docs.rocket.chat/installing-and-updating/docker-containers
# image and compose: https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml

version: '3.8'

services:
  rocketchat:
    image: rocket.chat:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_HTTP_PORT}:3000
    volumes:
      - rocketchat:/app
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:${DB_MONGO_PORT}/rocketchat?replicaSet=rs01
      - MONGO_OPLOG_URL=mongodb://mongo:${DB_MONGO_PORT}/local?replicaSet=rs01
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:${DB_MONGO_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    volumes:
      - mongo:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs01

  mongo-init-replica:
    image: mongo:${DB_MONGO_VERSION}
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs01'', members: [ { _id: 0, host: ''mongo:27017'' } ]})"'
    depends_on:
      - mongo
      
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  rocketchat:
  mongo:
